name: XC2N1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  OAS: ${{ vars.OAS }}-${{ vars.OASVER }}.json

jobs:
  # This workflow contains a single job called "build"
  XC_Pull:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
            
      - name: Set variables 
        run: |
          # echo "XC_BEARER_TOKEN=`echo -n "${{ secrets.XC_APITOKEN }}`" >> $GITHUB_ENV
          export OAS="${{ vars.OAS }}-${{ vars.OASVER }}"

      - name: Get the OAS
        run: |
          curl -X GET --location 'https://${{ secrets.XC_TENANT }}/api/object_store/namespaces/${{vars.NAMESPACE}}/stored_objects/swagger/${{vars.OAS}}/${{vars.OASVER}}' -H 'Authorization: Bearer APIToken ${{ secrets.XC_APITOKEN }}' -o ./xc2n1/oas/${{ env.OAS }}
        working-directory: ${{ github.workspace }}

      - name: Commit and Push the OAS
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .json
          git commit -m 'Committing updated OAS ${{ env.OAS }}'
          git push